var FEFE_POSTFIX_QUOTES = [
    ' (Danke, Christian)',
    ' (Danke, Arno)',
    ' WAS FÜR EINE ELENDE FRECHHEIT!!',
    ' OH NEIN!!!',
    ' Lest euch die Details durch!',
    ' Das ist ja mal eine ... ambitionierte Planung *hust* :-)',
    ' Da bleibt also nur eine Erklärung: Klarer Fall von Selbstmord.',
    ' Da weiß man, wohin die Reise geht!',
    ' NEIN!!1! Also DAMIT konnte ja wohl NIEMAND rechnen!',
    ' *grusel*',
    ' Was für eine Frechheit. (Danke, Mathias)',
    ' HARR HARR HARR',
    ' m( (Danke, Dennis)',
    ' Das hätte ich jetzt nicht gedacht.',
    ' BWAHAHAHA',
    ' Meine Damen und Herren, Ihre Steuergelder bei der Arbeit',
    ' Seufz.',
    ' Wie geil ist DAS denn? HAHAHAHAHA',
    ' Na also DAMIT konnte ja wohl NIEMAND rechnen!1!! m(',
    ' Nein, wirklich!',
    ' *STRIKE*',
    ' Das wird euch jetzt sicher genau so überraschen wie mich!',
    ' Na ganz groß. (Danke, Andreas)',
    ' Hups!',
    ' Und auch die Rhetorik drumherum erinnert an Deutschland vor 80 Jahren.',
    ' Da bleibt kein Auge trocken!',
    ' Kann man sich gar nicht ausdenken, sowas!',
    ' Ich sage euch, dieser Antisemitismus immer! ÜBERALL!',
    ' Na dann ist der Major Consensus Narrative ja hergestellt und die Fakten spielen keine Rolle mehr.',
    ' Nee, klar. Bestimmt ein Computerfehler!1!!',
    ' Nee, klar.',
    ' WTF?',
    ' (Links werden nachgereicht)',
    ' Was glauben die eigentlich, wozu sie da sind?!?',
    ' Immer wieder erschütternd, wie tief Menschen sinken können.',
    ' Das geht ausgerechnet aus einem BKA-Report hervor.',
    ' Genau, und DAS ist ein SKANDAL sondergleichen!',
    ' Also DAMIT konnte ja wohl NIEMAND rechnen!',
    ' OMFG',
    ' SCHANDE! SCHANDE! SCHANDE!',
    ' DIE BESTEN DER BESTEN DER BESTEN SIR!',
    ' Wer hätte das gedacht!!!!11!!!!1!',
    ' Natürlich bestand zu keinem zeitpunkt gefahr für die bevölkerung',
    ' Erinnert ein bißchen an die Geschichten vom Kriegsende, als die Soldaten der Roten Armee auf dem Heimweg die Wasserhähne abgeschraubt haben sollen, um sie dann zuhause in die Wand zu schrauben und einen Wasserstrahl zu erwarten.',
    ' (Danke Frank)',
    ' Liest sich wie Kafka.',
    ' m(',
    ' Aber das ist natürlich was VÖLLIG anderes. Bei den Chinesen ist das demokratiefeindliche Unterdrückungsgewaltdiktatur. Bei UNS hingegen ist das, äh, ... oh schau, schon SO spät!1!! *verdünnisier* (Danke, Bernhard)',
    '  Soso. OH DIE SCHMERZEN!!!',
    ' Aha. Soso.',
    ' Tolles Land haben wir da. (Danke, Christian)',
    ' Vielen Dank an der Stelle an Netzpolitik.org, ihr seid Helden!',
    ' o_O',
    ' Sehr erfreulich!',
    ' Phew! Ich hätte mir da fast Sorgen gemacht.',
    ' Na SO ein Zufall!',
    ' Was zur Hölle?!',
    ' DAS geht ja mal GAR nicht!',
    ' Meine Überraschung über diese Meldung lässt sich kaum in Worte fassen, so enorm ist sie.',
    ' Popcorn!',
    ' Klassische Externalisierung von Kosten.',
    ' Solche Leute laufen frei rum!',
    ' Klingt für mich plausibel.',
    ' Wow!',
    ' *fazialpalmier*',
    ' Es besteht also keinerlei Gefahr für die Bevölkerung oder die Umwelt. Na dann.',
    ' Un-glaub-lich!',
    ' Na dann ist ja alles klar.',
    ' *Stöhn*',
    ' Na SOWAS! Also DAMIT konnte ja wohl NIEMAND rechnen!1!!',
    ' Die beste Demokratie, die man für Geld kaufen kann!1!!',
    ' Ähnlich schlimm wie Marktforscher und die GEMA.',
    ' Wait, what?!',
    ' Das muss man sich mal auf der Zunge zergehen lassen!',
    ' *popcornhol*',
    ' Es bestehe keinerlei Gefahr für die Bevölkerung!1!!',
    ' PS: Das läuft diesmal nicht über unser altes CDN, es sollte also genug Bandbreite für alle da sein.',
    ' Äh, wie meinen?',
    ' Ich finde das keine schlechte Idee',
    ' Haben die alle kein Selbstwertgefühl?!',
    ' Auslöser ist natürlich die Contentmafia. Wer auch sonst.',
    ' Völlig klar, das ist versuchter Totschlag, ach was sage ich, Terrorismus! Schaltet den Staatsschutz ein!!1!',
    ' Ich finde das vernünftig.',
    ' Na klaaaaar. Keinerlei Gefahr für die Bevölkerung, natürlich nicht.',
    ' Unfassbar.',
    ' Überraschung!',
    ' Oh und wie war das noch gleich mit "der Markt regelt das"?',
    ' Schön!',
    ' Und deshalb muss diese CDU endlich weg.',
    ' OMFG. Offensichtlich bin ich noch nicht zynisch genug.',
    ' Ich finde das ja unglaublich, wie diese Leute morgens in den Spiegel gucken können.',
    ' So weggetreten kann doch keiner sein.',
    ' Sprecht mir also nach: Antiviren sind Snake Oil.',
    ' Sprecht mir also nach: Code Signing ist Snake Oil :-)',
    ' Ich halte das alles für Snake Oil, schlimmer noch, für aktiv sicherheitsreduzierend.',
    ' *popcorngreif*'
];

var FEFE_PREFIX_QUOTES = [
	'Was zur Hölle?! ',
    'Fnord des Tages: ',
    'Fazialpalmierung der Woche: ',
    'Ach nee. Na sowas: ',
    'Das wird euch jetzt sicher genau so überraschen wie mich: ',
    'Was wie ein Witz beginnt, wird ab dem 5. Absatz plötzlich spannend: ',
    'Währenddessen im Fox News-Paralleluniversum: ',
    'WTF? ',
    'Klarer Fall von Selbstmord: ',
    'Hier kommt gerade eine erschütternde Mail von jemandem rein: ',
    'Die gute Nachricht: ',
    'Sehr erfreulich: ',
    'Wir sind alle so gut wie tot! ',
    'Lacher des Tages: ',
    'DAS erklärt EINIGES: ',
    'Weia: ',
    'Na super!1!! ',
    'Un-glaub-lich! ',
    'HAHAHAHA OMG das ist ja der Knüller: ',
    'Hände hoch, wer von dieser Reuters-Eilmeldung überrascht ist: ',
    'Na SOWAS! Also DAMIT konnte ja wohl NIEMAND rechnen!1!! - ',
    'NA ENDLICH macht das mal jemand! ',
    'Lolwut!? ',
    'Die BESTEN der BESTEN der BESTEN, SIR: ',
    'Spannendes Detail: ',
    'Na DAS passt ja mal wieder wie Arsch auf Eimer: ',
    'Al Jazeera gerüchtet, ',
    'Geht weiter mit dem Versagertum: ',
    'Äh, WTF?! ',
    'Grusel des Tages: ',
    'Schlechte Ausrede des Tages: ',
    'Mir wird gerade eine schöne Anekdote zugetragen, von einer Veranstaltung gestern: ',
    'OH DIE SCHMERZEN! ',
    'Wollt ihr mal was wirklich schlimmes lesen? Ja? Genau der richtige Tag für das Beobachten von Auffahrunfällen? Dann hab ich was für euch! ',
    'Einsicht des Tages: ',
    'Whoa, dem ehemaligen Nachrichtenmagazin ist aufgefallen: ',
    'Ich sage ja schon seit vielen Jahren, dass Antiviren Snake Oil sind. '
];

var FEFE_INFIX_QUOTES = [
    ' (HAHAHAHAHAHAHAHAHAHA) ',
    ' (HAHAHA) ',
    ' (HAHA) ',
    ' WTF? ',
    ' Wait, WHAT?! ',
    ' Wow. ',
    ' Harrharrharr. '
];

var FEFE_LINK_WARNINGS = [
    ' (Die Webseite ist auf kroatisch, Google Translate hilft)',
    ' Die Seite war auch schon vor meinem Link langsam!!',
    ' Update: Jetzt geht die Webseite wieder aber der PDF-Link von gestern nicht mehr. Dieser ranzige Cloud-Mist immer!1!!',
    ' (der Kommentar im Kasten unter dem Artikel). Im Artikel selbst ist vor allem der letzte Absatz interessant, finde ich',
    ' Update: Das ist, wie man schon an der URL sehen kann, etwas älter',
    ' Update: besserer Link',
    ' Update: Quelle auf Englisch',
    ' Update: Betrieben übrigens von einem Spackeria-Mitglied, wie mir gerade jemand erzählt',
    ' Update: Angeblich kamen die Daten von "BlueToad"',
    ' Update: Dieser Artikel war kurzzeitig weg, sorry, mein Fehler',
    ' Hatte ich hier schon aber geht in der Presse völlig unter, daher nochmal nachtreten',
    ' Update: Besserer Link',
    ' Update: Hups, Link vergessen.',
    ' Update: War ein Fake',
    ' (Achtung: Google Plus)',
    ' (Achtung: Link geht zu Google+)',
    ' Update: Netzpolitik.org hat mal recherchiert',
    ' (auf das Bild klicken!)',
    ' Ich bitte um Verzeihung zu dem Snake-Oil-Vendor-Link, aber die einzige andere URL, die ich hatte, war zu einem angeblichen SQL-Dump'
];
